-- =====================================================================
-- REQ-010 — Normalise mat_aspect_id / aspect_code values containing
--            characters outside the permitted set
--
-- Author:  Claude Code (backend)
-- Date:    2026-08-26
-- Status:  NOT RUN. Written for manual application per milestone plan
--          §2.4. Review, fill in section 2, then apply.
--
-- Target:  Assurly production (MySQL 8, Cloud SQL, europe-west2)
-- Tables:  mat_aspects (PK rewrite), mat_standards (FK follow),
--          user_aspect_assignments (FK follow)
-- =====================================================================
--
-- WHY THIS EXISTS
--
--   mat_aspect_id is minted as {MAT}-{ASPECT_CODE} and travels in the URL
--   path. aspect_code was previously accepted with no character
--   constraint, so ids exist containing spaces, '&' and '\'. REQ-010 adds
--   ASPECT_CODE_PATTERN (^[A-Za-z0-9_]{2,10}$) at the point of creation;
--   this migration brings existing rows into line with it.
--
-- READ THIS BEFORE DECIDING TO RUN IT
--
--   This migration is NOT what unblocks the reported 404. The call-site
--   encodeURIComponent fix in the same commit does that on its own: a
--   percent-encoded '\' or '&' is decoded by uvicorn back to the literal
--   character, the Starlette route pattern [^/]+ matches it, and the
--   parameterised lookup finds the row. Verified by reasoning through the
--   request path, not by execution.
--
--   The one case encoding CANNOT repair is a literal '/' in the id: %2F is
--   unquoted to '/' before routing, which adds a path segment and misses
--   the route regardless. If section 2 finds no row containing '/', this
--   migration is hygiene — worth doing so the data matches the new rule
--   and so correctness stops depending on every future call site
--   remembering to encode, but not urgent, and safe to schedule.
--
-- =====================================================================
-- 1. DISCOVERY — run first, on a read replica or with SELECT only.
--    Nothing below can be written until you know what is affected.
-- =====================================================================

-- 1a. Aspects whose id or code falls outside the permitted set.
--     The id is allowed one hyphen (the {MAT}-{CODE} separator); the code
--     is allowed none.
SELECT
    ma.mat_aspect_id,
    ma.mat_id,
    ma.aspect_code,
    ma.aspect_name,
    ma.is_active,
    ma.source_aspect_id IS NULL AS is_custom,
    (SELECT COUNT(*) FROM mat_standards ms
      WHERE ms.mat_aspect_id = ma.mat_aspect_id)            AS standards_total,
    (SELECT COUNT(*) FROM mat_standards ms
      WHERE ms.mat_aspect_id = ma.mat_aspect_id
        AND ms.is_active = 1)                                AS standards_active,
    (SELECT COUNT(*) FROM user_aspect_assignments ua
      WHERE ua.mat_aspect_id = ma.mat_aspect_id)             AS assignments
FROM mat_aspects ma
WHERE ma.aspect_code NOT REGEXP '^[A-Za-z0-9_]{2,10}$'
   OR ma.mat_aspect_id NOT REGEXP '^[A-Za-z0-9_]+-[A-Za-z0-9_]{2,10}$'
ORDER BY ma.mat_id, ma.mat_aspect_id;

-- 1b. Of those, the ids that encoding cannot rescue. If this returns rows,
--     the migration is a fix, not hygiene — prioritise accordingly.
SELECT mat_aspect_id, aspect_code, aspect_name
FROM mat_aspects
WHERE mat_aspect_id LIKE '%/%'
   OR mat_aspect_id LIKE '%#%'
   OR mat_aspect_id LIKE '%?%';

-- 1c. Archive-renamed rows. These end '-deleted-<unix_ts>' and must NOT be
--     normalised by the generic rule — the suffix is meaningful and the
--     rows are already soft-deleted. Exclude them from section 2 unless
--     you have a specific reason not to.
SELECT mat_aspect_id, aspect_code, is_active
FROM mat_aspects
WHERE mat_aspect_id LIKE '%-deleted-%';

-- =====================================================================
-- 2. THE RENAME — hand-written, one block per affected row.
--
--    Deliberately not generated by a transform. A blind
--    REGEXP_REPLACE could collide two codes onto one id (e.g.
--    'IT & Data' and 'IT-Data' both reducing to 'ITDATA') and silently
--    violate the PK, and the correct new code for a given aspect is a
--    naming decision, not a mechanical one. Fill this in from the
--    output of 1a.
--
--    Worked example for the reported case; delete or adapt.
--    Choose new codes that satisfy ^[A-Za-z0-9_]{2,10}$.
-- =====================================================================

-- 2a. Collision check. MUST return zero rows before proceeding.
--     Repeat for every (mat_id, new_code) pair you intend to use.
SELECT mat_aspect_id, aspect_code
FROM mat_aspects
WHERE mat_id = 'HLT'                       -- << target MAT
  AND UPPER(aspect_code) = 'IT_DATA';      -- << intended new code

START TRANSACTION;

-- InnoDB enforces fk_mat_standards_aspect and fk_assignments_aspect with
-- ON UPDATE NO ACTION (see data model §20.1) — NOT ON UPDATE CASCADE. A
-- parent PK update is therefore REJECTED while children reference it, and
-- the children cannot be repointed first because the new parent id does
-- not exist yet. Suspending the check for this session is the least
-- invasive way through; the alternative is dropping and re-adding both
-- constraints, which is heavier and no safer.
--
-- The setting is session-scoped and reverted in section 3. Every child
-- row is updated explicitly below — nothing relies on cascade behaviour.
SET FOREIGN_KEY_CHECKS = 0;

-- Parent.
UPDATE mat_aspects
SET mat_aspect_id = 'HLT-IT_DATA',         -- << new id: {MAT}-{NEW_CODE}
    aspect_code   = 'IT_DATA',             -- << new code
    updated_at    = NOW()
WHERE mat_aspect_id = 'HLT-IT & DATA';     -- << old id, verbatim from 1a

-- Children — both FKs, active and inactive rows alike.
UPDATE mat_standards
SET mat_aspect_id = 'HLT-IT_DATA'
WHERE mat_aspect_id = 'HLT-IT & DATA';

UPDATE user_aspect_assignments
SET mat_aspect_id = 'HLT-IT_DATA'
WHERE mat_aspect_id = 'HLT-IT & DATA';

-- Repeat the three statements above for each further affected row.

-- =====================================================================
-- 3. VERIFY BEFORE COMMITTING — still inside the transaction.
--    If any check fails, ROLLBACK. Do not commit and repair afterwards.
-- =====================================================================

SET FOREIGN_KEY_CHECKS = 1;

-- 3a. No orphaned children. Both MUST return zero.
SELECT ms.mat_standard_id, ms.mat_aspect_id
FROM mat_standards ms
LEFT JOIN mat_aspects ma ON ms.mat_aspect_id = ma.mat_aspect_id
WHERE ma.mat_aspect_id IS NULL;

SELECT ua.assignment_id, ua.mat_aspect_id
FROM user_aspect_assignments ua
LEFT JOIN mat_aspects ma ON ua.mat_aspect_id = ma.mat_aspect_id
WHERE ma.mat_aspect_id IS NULL;

-- 3b. No non-conforming rows left (excluding archive renames from 1c).
SELECT mat_aspect_id, aspect_code
FROM mat_aspects
WHERE mat_aspect_id NOT LIKE '%-deleted-%'
  AND (aspect_code NOT REGEXP '^[A-Za-z0-9_]{2,10}$'
       OR mat_aspect_id NOT REGEXP '^[A-Za-z0-9_]+-[A-Za-z0-9_]{2,10}$');

-- 3c. Standard counts unchanged. Compare against 1a's standards_total.
SELECT mat_aspect_id, COUNT(*) AS standards_total
FROM mat_standards
WHERE mat_aspect_id IN ('HLT-IT_DATA')     -- << new ids
GROUP BY mat_aspect_id;

-- Only when 3a and 3b return zero rows and 3c matches:
-- COMMIT;
--
-- Otherwise:
-- ROLLBACK;

-- =====================================================================
-- 4. ROLLBACK NOTE
-- =====================================================================
--
-- BEFORE COMMIT
--   ROLLBACK; — restores everything, including FOREIGN_KEY_CHECKS, which
--   is session state and is reset when the session ends regardless.
--
-- AFTER COMMIT
--   The change is a rename, so it reverses exactly by swapping the old
--   and new ids in section 2 and re-running with the same
--   FOREIGN_KEY_CHECKS suspension. Nothing is dropped and no row is
--   deleted, so no data can be lost by reversing it. Keep the completed
--   section 2 as the reverse script.
--
--   Reverse order does not matter (parent and children move together
--   inside one transaction with checks suspended), but keep the same
--   three-statement grouping per aspect so a partial reversal is not
--   possible.
--
-- TAKE A BACKUP FIRST
--   Follow the convention used for earlier schema work (data model §21
--   records `assurly_backup_v3` for the April 2026 pass). At minimum:
--     mysqldump --single-transaction --set-gtid-purged=OFF \
--       <db> mat_aspects mat_standards user_aspect_assignments \
--       > req010_pre_migration.sql
--
-- APPLICATION IMPACT
--   Aspect ids are not persisted client-side beyond the lifetime of a
--   page, so no cache invalidation is required. Any user holding an open
--   edit dialog for a renamed aspect at the moment of the migration will
--   get a 404 on save and must reload — the window is small and the
--   failure is safe, but prefer a quiet period.
--
--   No deploy ordering constraint: the REQ-010 code change is compatible
--   with both old and new ids, so this migration can be applied before or
--   after that release.
--
-- =====================================================================
-- 5. RELATED DEFECT FOUND WHILE WRITING THIS — NOT FIXED HERE
-- =====================================================================
--
--   delete_aspect (main.py) archive-renames a custom aspect's PK to
--   '{id}-deleted-{ts}'. It guards on ACTIVE standards only (409 when
--   any exist), but fk_mat_standards_aspect is ON UPDATE NO ACTION, so
--   an aspect with zero active and one or more INACTIVE standards will
--   fail the rename on the foreign key and surface as a generic 500 from
--   the catch-all handler.
--
--   Same root cause as this migration: a PK rewrite under a
--   non-cascading FK. Reported as a finding for triage, deliberately not
--   fixed under REQ-010.
